In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import string

In [2]:
df = pd.read_csv('Jobstreet_Ziig.csv')

In [96]:
jobstreet_df = df.copy()

In [97]:
jobstreet_df = jobstreet_df.reset_index(drop=True)

In [98]:
jobstreet_df = jobstreet_df.drop('Unnamed: 0', axis=1)

In [99]:
jobstreet_df.describe()

,Company,Title,Location,Address,Industry,Job Description,Seniority,Salary,Requirements,JD
count,2573,2573,2573,2573,2573,2573,2573,2573,707,2573
unique,429,1135,200,394,51,1316,53,195,333,1288
top,(Recruitment Firm),Business Analyst,Singapore - Central,None,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 3 years (Senior Executive),Aboveexpectedsalary,A degree in business management or related fi...,- Gaining and maintaining an understanding of ...
freq,290,75,903,778,1389,12,275,651,9,14

In [100]:
jobstreet_df.isnull().sum()

Company               0
Title                 0
Location              0
Address               0
Industry              0
Job Description       0
Seniority             0
Salary                0
Requirements       1866
JD                    0
dtype: int64

In [101]:
jobstreet_df = jobstreet_df.drop('Requirements', axis=1)

In [102]:
jobstreet_df.head()

,Company,Title,Location,Address,Industry,Job Description,Seniority,Salary,JD
0,Career Edge Asia Pte Ltd,Senior Data Analyst ($7K - $8K / CBD/ MNC ) re...,Singapore - Across Singapore,None,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 3 years (Senior Executive),6000-8000,Responsibilities Responsible for dashboards an...
1,YGP Pte Ltd,Data Analyst,Singapore - Central - Downtown Core - Tanjong ...,79 Anson Road Singapore,Automobile/Automotive Ancillary/Vehicle,"<div class=""unselectable wrap-text"" id=""job_de...",Min 2 years (Junior Executive),3000-4000,Application Management\r\n\r\n Register & gath...
2,None,Data Analyst,Singapore - Central,2 Bukit Merah Central Podium #04-00,Wood/Fibre/Paper,"<div class=""unselectable wrap-text"" id=""job_de...",Entry Level,3500-4900,Key Responsibilities Report to the Market Anal...
3,nSearch Global Pte Ltd,Senior Business Analyst - Data Analytics / Pro...,Singapore - Central,None,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 5 years (Senior Executive),Aboveexpectedsalary,One of Asia-Pacifics leading organizations is ...
4,Adecco Personnel Pte Ltd.,Data Analyst- Pivot Table/ V-Look-up,Singapore - Across Singapore - Singapore,None,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Entry Level,3000-5000,The Opportunity Adecco is partnering with a r...

In [103]:
# Import the regex module
import re

## Feature Engineering

### Min years Experience feature

In [ ]:
## Imputed Junior Executive and Entry Level as Min years of Exp = 1
## 'Senior Executive', 'Senior Manager', 'Manager', 'None' = np.nan

In [104]:
jobstreet_df.Seniority.value_counts()

Min 3 years (Senior Executive)     275
Min 5 years (Senior Executive)     251
Min 2 years (Junior Executive)     229
Min 2 years (Senior Executive)     179
Min 1 year (Junior Executive)      166
Junior Executive                   159
Entry Level                        151
Min 3 years (Junior Executive)     150
Min 5 years (Manager)              110
Min 4 years (Senior Executive)      94
Min 1 year (Manager)                68
Min 3 years (Manager)               56
Senior Executive                    48
Min 1 year (Senior Executive)       44
Senior Manager                      41
Min 4 years (Manager)               37
Min 6 years (Senior Executive)      35
Min 2 years (Manager)               32
Min 7 years (Senior Executive)      32
Min 5 years (Non-Executive)         31
Min 2 years (Non-Executive)         31
Min 3 years (Non-Executive)         30
Min 8 years (Senior Executive)      29
Min 1 year (Entry Level)            29
Min 4 years (Junior Executive)      27
Min 5 years (Junior Executive)      24
Min 3 years (Senior Manager)        23
Min 5 years (Senior Manager)        21
Min 8 years (Senior Manager)        19
Manager                             16
Min 1 year (Non-Executive)          15
Min 10 years (Senior Manager)       15
Min 8 years (Manager)               13
Min 6 years (Manager)               11
Min 7 years (Manager)               10
Min 10 years (Manager)               8
Min 4 years (Non-Executive)          8
Min 7 years (Junior Executive)       7
Min 10 years (Senior Executive)      6
Min 6 years (Non-Executive)          6
Min 3 years (Entry Level)            5
Min 8 years (Non-Executive)          5
Min 5 years (Entry Level)            5
Min 12 years (Senior Executive)      4
Min 7 years (Non-Executive)          4
Min 4 years (Senior Manager)         3
None                                 2
Min 2 years (Entry Level)            2
Min 7 years (Senior Manager)         2
Min 15 years (Senior Manager)        2
Min 8 years (Junior Executive)       1
Min 15 years (Junior Executive)      1
Min 9 years (Manager)                1
Name: Seniority, dtype: int64

In [111]:
jobstreet_df['Seniority'].values[0]

'Min 3 years (Senior Executive)'

In [112]:
# Find all digits in my_string and print the result
digits = r"\d+"
print(re.findall(digits, jobstreet_df['Seniority'].values[0]))

['3']

In [129]:
def juniorexec_or_entry(x):
    if x == 'Entry Level' or x == 'Junior Executive':
        return 1
    elif x in ['Senior Executive', 'Senior Manager', 'Manager', 'None']:
        return np.nan
    else:
        return int(''.join(re.findall(digits, x)))

In [130]:
## MINIMUM YEARS OF EXPERIENCE FEATURE
jobstreet_df['Min Years Exp'] = jobstreet_df['Seniority'].apply(juniorexec_or_entry)

In [133]:
jobstreet_df['Min Years Exp'].isnull().sum()

107

In [135]:
jobstreet_df['Min Years Exp'].value_counts()

1.0     632
3.0     539
2.0     473
5.0     442
4.0     169
8.0      67
7.0      55
6.0      52
10.0     29
12.0      4
15.0      3
9.0       1
Name: Min Years Exp, dtype: int64

In [ ]:
jobstreet_df[jobstreet_df]

### Job Level Feature

In [141]:
inbracket_pattern = '\((.*?)\)'

In [149]:
re.findall(inbracket_pattern, jobstreet_df['Seniority'].values[0])[0]

'Senior Executive'

In [150]:
def job_level(x):
    if x in ['Junior Executive','Entry Level','Senior Executive', 'Senior Manager', 'Manager', 'None']:
        return x
    else:
        return re.findall(inbracket_pattern, x)[0]

In [151]:
jobstreet_df['Job Level'] = jobstreet_df['Seniority'].apply(job_level)

In [153]:
jobstreet_df['Job Level'].value_counts()

Senior Executive    997
Junior Executive    764
Manager             362
Entry Level         192
Non-Executive       130
Senior Manager      126
None                  2
Name: Job Level, dtype: int64

In [155]:
jobstreet_df

,Company,Title,Location,Address,Industry,Job Description,Seniority,Salary,JD,Min Years Exp,Job Level
0,Career Edge Asia Pte Ltd,Senior Data Analyst ($7K - $8K / CBD/ MNC ) re...,Singapore - Across Singapore,None,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 3 years (Senior Executive),6000-8000,Responsibilities Responsible for dashboards an...,3.0,Senior Executive
1,YGP Pte Ltd,Data Analyst,Singapore - Central - Downtown Core - Tanjong ...,79 Anson Road Singapore,Automobile/Automotive Ancillary/Vehicle,"<div class=""unselectable wrap-text"" id=""job_de...",Min 2 years (Junior Executive),3000-4000,Application Management\r\n\r\n Register & gath...,2.0,Junior Executive
2,None,Data Analyst,Singapore - Central,2 Bukit Merah Central Podium #04-00,Wood/Fibre/Paper,"<div class=""unselectable wrap-text"" id=""job_de...",Entry Level,3500-4900,Key Responsibilities Report to the Market Anal...,1.0,Entry Level
3,nSearch Global Pte Ltd,Senior Business Analyst - Data Analytics / Pro...,Singapore - Central,None,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 5 years (Senior Executive),Aboveexpectedsalary,One of Asia-Pacifics leading organizations is ...,5.0,Senior Executive
4,Adecco Personnel Pte Ltd.,Data Analyst- Pivot Table/ V-Look-up,Singapore - Across Singapore - Singapore,None,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Entry Level,3000-5000,The Opportunity Adecco is partnering with a r...,1.0,Entry Level
5,(Recruitment Firm),Data Analysts- Up to $3500 @Clementi (3 months...,Singapore - Central,8 Marina View #11-01 Asia Square Tower 1 Singa...,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 2 years (Junior Executive),3000-3500,Set up efficient process to compare of large c...,2.0,Junior Executive
6,RECRUIT EXPRESS PTE LTD,Data Analyst (Perm) *GOOD CAREER PROSPECT*,Singapore - Central,None,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 1 year (Senior Executive),3000-5000,*** GOOD CAREER PROSPECT AWAITS RIGHT CANDIDAT...,1.0,Senior Executive
7,Sopra Steria Asia Pte Ltd,Data Analyst,Singapore - West - Others - One North,"3, Fusionopolis Way Symbiosis #12-27","Consulting (IT, Science, Engineering & Technical)","<div class=""unselectable wrap-text"" id=""job_de...",Min 7 years (Junior Executive),Aboveexpectedsalary,Requirements\r\n\r\n\r\n\r\nDevelop data minin...,7.0,Junior Executive
8,United Overseas Bank Limited (UOB),"VP/AVP, EDAG Project Analyst, Data Management ...",Singapore - Across Singapore - Singapore,None,Banking/Financial Services,"<div class=""unselectable wrap-text"" id=""job_de...",Min 5 years (Senior Executive),Aboveexpectedsalary,Job DescriptionThe Data Management Office is a...,5.0,Senior Executive
9,United Overseas Bank Limited (UOB),"VP, Business Data Analyst, Enterprise Data Str...",Singapore - Across Singapore - Singapore,None,Banking/Financial Services,"<div class=""unselectable wrap-text"" id=""job_de...",Min 7 years (Senior Executive),Aboveexpectedsalary,TheData Management Office (DMO)is a business f...,7.0,Senior Executive
10,DBS Bank Limited,"Senior Associate/Associate, MIS Analyst, Group...",Singapore - Across Singapore - singapore,None,Banking/Financial Services,"<div class=""unselectable wrap-text"" id=""job_de...",Senior Executive,None,Business Function Group Technology and Operat...,NaN,Senior Executive
11,United Overseas Bank Limited (UOB),"VP/AVP, EDAG Project Analyst, Data Management ...",Singapore - Across Singapore - Singapore,None,Banking/Financial Services,"<div class=""unselectable wrap-text"" id=""job_de...",Min 5 years (Senior Executive),Aboveexpectedsalary,Job DescriptionThe Data Management Office is a...,5.0,Senior Executive
12,United Overseas Bank Limited (UOB),"VP, Data Analyst, GTO - (140c50a7-c509-4f92-a)",Singapore - Across Singapore - Singapore,None,Banking/Financial Services,"<div class=""unselectable wrap-text"" id=""job_de...",Senior Manager,None,"Proven working experience as a data analyst, w...",NaN,Senior Manager
13,StarHub Ltd,Data Analyst / Scientist - (1800000Q),Singapore - Across Singapore - Singapore,None,Telecommunication,"<div class=""unselectable wrap-text"" id=""job_de...",Senior Executive,None,Anticipates the clients' needs and formulates ...,NaN,Senior Executive
14,(Recruitment Firm),"HRIS, Data Analyst (IT Industry, MNC, West Are...",Singapore - West,1 Wallich Street #09-02 Guoco Tower Singapore ...,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 3 years (Senior Executive),2800-5000,Responsibilities Provide insights of HR Trends...,3.0,Senior Executive
15,(Recruitment Firm),Data Analysts- Up to $3500 @Clementi (3 months...,Singapore - Central,8 Marina View #11-01 Asia Square Tower 1 Singa...,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 3 years (Junior Executive),3000-3500,Set up efficient process to compare of large c...,3.0,Junior Executive
16,(Recruitment Firm),"Supply Chain Data Analyst, 3 Months Contract (...",Singapore - Central,8 Marina View #11-01 Asia Square Tower 1 Singa...,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 2 years (Senior Executive),2800-3500,Set up efficient process to compare of large c...,2.0,Senior Executive
17,Talentvis Singapore Pte Ltd,"Marketing Analyst - US Global MNC (4 months, F...",Singapore - Central - Raffles Place,79 Anson Road Singapore,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 3 years (Junior Executive),Aboveexpectedsalary,"Our client, is a professional consulting busin...",3.0,Junior Executive
18,United Overseas Bank Limited (UOB),"Data Analyst, Digital Bank - (06d9a2f0-d24e-4d...",Singapore - Across Singapore - Singapore,None,Banking/Financial Services,"<div class=""unselectable wrap-text"" id=""job_de...",Senior Manager,None,You will be part of a very vibrant and dynamic...,NaN,Senior Manager
19,(Recruitment Firm),Data Analysts- Up to $3500 @Clementi (3 months...,Singapore - Central,8 Marina View #11-01 Asia Square Tower 1 Singa...,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 2 years (Junior Executive),3000-3500,Set up efficient process to compare of large c...,2.0,Junior Executive
20,Career Edge Asia Pte Ltd,Senior Data Analyst ($7K - $8K / CBD/ MNC ) re...,Singapore - Across Singapore,None,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 3 years (Senior Executive),6000-8000,Responsibilities Responsible for dashboards an...,3.0,Senior Executive
21,YGP Pte Ltd,Data Analyst,Singapore - Central - Downtown Core - Tanjong ...,79 Anson Road Singapore,Automobile/Automotive Ancillary/Vehicle,"<div class=""unselectable wrap-text"" id=""job_de...",Min 2 years (Junior Executive),3000-4000,Application Management\r\n\r\n Register & gath...,2.0,Junior Executive
22,None,Data Analyst,Singapore - Central,2 Bukit Merah Central Podium #04-00,Wood/Fibre/Paper,"<div class=""unselectable wrap-text"" id=""job_de...",Entry Level,3500-4900,Key Responsibilities Report to the Market Anal...,1.0,Entry Level
23,nSearch Global Pte Ltd,Senior Business Analyst - Data Analytics / Pro...,Singapore - Central,None,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 5 years (Senior Executive),Aboveexpectedsalary,One of Asia-Pacifics leading organizations is ...,5.0,Senior Executive
24,Adecco Personnel Pte Ltd.,Data Analyst- Pivot Table/ V-Look-up,Singapore - Across Singapore - Singapore,None,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Entry Level,3000-5000,The Opportunity Adecco is partnering with a r...,1.0,Entry Level
25,(Recruitment Firm),Data Analysts- Up to $3500 @Clementi (3 months...,Singapore - Central,8 Marina View #11-01 Asia Square Tower 1 Singa...,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 2 years (Junior Executive),3000-3500,Set up efficient process to compare of large c...,2.0,Junior Executive
26,RECRUIT EXPRESS PTE LTD,Data Analyst (Perm) *GOOD CAREER PROSPECT*,Singapore - Central,None,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 1 year (Senior Executive),3000-5000,*** GOOD CAREER PROSPECT AWAITS RIGHT CANDIDAT...,1.0,Senior Executive
27,Sopra Steria Asia Pte Ltd,Data Analyst,Singapore - West - Others - One North,"3, Fusionopolis Way Symbiosis #12-27","Consulting (IT, Science, Engineering & Technical)","<div class=""unselectable wrap-text"" id=""job_de...",Min 7 years (Junior Executive),Aboveexpectedsalary,Requirements\r\n\r\n\r\n\r\nDevelop data minin...,7.0,Junior Executive
28,United Overseas Bank Limited (UOB),"VP/AVP, EDAG Project Analyst, Data Management ...",Singapore - Across Singapore - Singapore,None,Banking/Financial Services,"<div class=""unselectable wrap-text"" id=""job_de...",Min 5 years (Senior Executive),Aboveexpectedsalary,Job DescriptionThe Data Management Office is a...,5.0,Senior Executive
29,United Overseas Bank Limited (UOB),"VP, Business Data Analyst, Enterprise Data Str...",Singapore - Across Singapore - Singapore,None,Banking/Financial Services,"<div class=""unselectable wrap-text"" id=""job_de...",Min 7 years (Senior Executive),Aboveexpectedsalary,TheData Management Office (DMO)is a business f...,7.0,Senior Executive
...,...,...,...,...,...,...,...,...,...,...,...
2543,Talent Trader Group Pte Ltd,Sales Executive/ Biomedical/ Microbiology/ Res...,Singapore - Across Singapore,None,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 2 years (Senior Executive),Aroundexpectedsalary,"Responsibilties Prospect, develop and drive sa...",2.0,Senior Executive
2544,Talent Trader Group Pte Ltd,Business Intelligent Analyst/ Data and Market ...,Singapore - Across Singapore,7500A Beach Road The Plaza #05-323 Singapore 1...,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 3 years (Junior Executive),2500-5000,- Gaining and maintaining an understanding of ...,3.0,Junior Executive
2545,Achieve Career Consultant Pte Ltd,"Sales Executive, Construction Materials (Leadi...",Singapore - Central,6 Shenton Way Tower 1 #39-03 Singapore 068809,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 2 years (Junior Executive),Belowexpectedsalary,Up to S$3.1K Base+AWS+variable bonuses!! 2-3yr...,2.0,Junior Executive
2546,NCS Pte Ltd,RPA Consultant,Singapore - North-East,5 Ang Mo Kio Street 62 NCS Hub,Computer/Information Technology (Software),"<div class=""unselectable wrap-text"" id=""job_de...",Entry Level,3200-4200,Job Description Facilitating workshops; workin...,1.0,Entry Level
2547,Panasonic Asia Pacific Pte Ltd,Intellectual Property (IP) Analyst,Singapore - East - Bedok - Bedok,202 Bedok South Avenue 1 Singapore 469332,Electrical & Electronics,"<div class=""unselectable wrap-text"" id=""job_de...",Min 3 years (Junior Executive),Aroundexpectedsalary,"Going beyond just providing good products, we ...",3.0,Junior Executive
2548,ST Electronics (Satcom & Sensor Systems) Pte Ltd,Data Scientist,Singapore - North-East - Ang Mo Kio,1 Ang Mo Kio Electronics Park Road Singapore,Electrical & Electronics,"<div class=""unselectable wrap-text"" id=""job_de...",Min 2 years (Senior Executive),Aboveexpectedsalary,Job Description Design and develop data analyt...,2.0,Senior Executive
2549,Talent Touche Pte Ltd,Sales Manager,Singapore - Central,101 Cecil Street Tong Eng Building #18-11 Spor...,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 5 years (Manager),Aroundexpectedsalary,Responsibilities Business development and grow...,5.0,Manager
2550,CVista HR Consulting Pte Ltd,"Senior HR Manager (East, MNC, Up to $8,000)",Singapore - East,None,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 8 years (Senior Manager),7000-8000,Key ResponsibilitiesEngage and partner with th...,8.0,Senior Manager
2551,RecruitPlus Consulting Pte Ltd,TALENT SPECIALIST(Recruitment Sales) – Up $5–1...,Singapore - Central,146 Robinson Road #08-01 Singapore 068909,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Entry Level,5000-10000,"$2,5003,000 Basic + High Commission + Performa...",1.0,Entry Level
2552,The Supreme HR Advisory Pte. Ltd.,Sales Executive 【Freight Forwarding / Logistic...,Singapore - Across Singapore,None,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Entry Level,1800-2800,Attractive Salary Package Company Benefits & I...,1.0,Entry Level
2553,(Recruitment Firm),Presales Consultant,Singapore - Central,8 Marina View #11-01 Asia Square Tower 1 Singa...,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 5 years (Senior Executive),4000-5600,SummaryThe applicant is responsible for provid...,5.0,Senior Executive
2554,Ackerman Global Search,Deputy Sales Manager | Control and Industrial ...,Singapore - Central,None,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 5 years (Senior Executive),4000-5600,Responsible for sales into the key markets ide...,5.0,Senior Executive
2555,None,Sales Manager (Pumps),Singapore - West - Singapore,"Jalan Puchong, 47100 Puchong, Selangor, Malaysia",Heavy Industrial/Machinery/Equipment,"<div class=""unselectable wrap-text"" id=""job_de...",Min 5 years (Manager),3500-6000,Overall ResponsibilityThe Sales Manager would ...,5.0,Manager
2556,Career International FOS Pte Ltd,Sales Executive | Construction Materials | B2B...,Singapore - Central,None,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 2 years (Junior Executive),Belowexpectedsalary,Sales ExecutiveJob Specifications At least 2 ...,2.0,Junior Executive
2557,RecruitPlus Consulting Pte Ltd,TALENT SPECIALIST (Recruitment Sales) – Up $5–...,Singapore - Central,146 Robinson Road #08-01 Singapore 068909,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Entry Level,5000-10000,"$2,5003,000 Basic + High Commission + Performa...",1.0,Entry Level
2558,SEARCH STAFFING SERVICES PTE. LTD,"Advanced Software Engineer, Global Technology ...",Singapore - North,"30 Raffles Place, #23-00, Chevron House, Singa...",Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 5 years (Junior Executive),4000-6000,We are representing a leading Medical Devices ...,5.0,Junior Executive
2559,P'nnacle Pte Ltd,"Sales Manager, Industrial Cleaning Equipment (...",Singapore - Central,1 Raffles Quay North Tower Level 25,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 4 years (Manager),Aboveexpectedsalary,"Develop sales strategy, maintain and grow sale...",4.0,Manager
2560,Career Trend Pte Ltd,Vice President - Business Development (Hotel o...,Singapore - Central - Central,Central,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 5 years (Senior Manager),10000-12000,RESPONSIBILITIES Ability to source and identif...,5.0,Senior Manager
2561,Talent Trader Group Pte Ltd,*URGENT* Sales Manager (Building Materials/ Ce...,Singapore - Across Singapore,7500A Beach Road The Plaza #05-323 Singapore 1...,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 2 years (Senior Executive),Aroundexpectedsalary,Administer and coordinate all readymix concret...,2.0,Senior Executive
2562,Talent Trader Group Pte Ltd,Sales Executive/ Biomedical/ Microbiology/ Res...,Singapore - Across Singapore,None,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 2 years (Senior Executive),Aroundexpectedsalary,"Responsibilties Prospect, develop and drive sa...",2.0,Senior Executive
2563,Talent Trader Group Pte Ltd,Business Intelligent Analyst/ Data and Market ...,Singapore - Across Singapore,7500A Beach Road The Plaza #05-323 Singapore 1...,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 3 years (Junior Executive),2500-5000,- Gaining and maintaining an understanding of ...,3.0,Junior Executive
2564,Achieve Career Consultant Pte Ltd,"Sales Executive, Construction Materials (Leadi...",Singapore - Central,6 Shenton Way Tower 1 #39-03 Singapore 068809,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 2 years (Junior Executive),Belowexpectedsalary,Up to S$3.1K Base+AWS+variable bonuses!! 2-3yr...,2.0,Junior Executive
2565,NCS Pte Ltd,RPA Consultant,Singapore - North-East,5 Ang Mo Kio Street 62 NCS Hub,Computer/Information Technology (Software),"<div class=""unselectable wrap-text"" id=""job_de...",Entry Level,3200-4200,Job Description Facilitating workshops; workin...,1.0,Entry Level
2566,Panasonic Asia Pacific Pte Ltd,Intellectual Property (IP) Analyst,Singapore - East - Bedok - Bedok,202 Bedok South Avenue 1 Singapore 469332,Electrical & Electronics,"<div class=""unselectable wrap-text"" id=""job_de...",Min 3 years (Junior Executive),Aroundexpectedsalary,"Going beyond just providing good products, we ...",3.0,Junior Executive
2567,ST Electronics (Satcom & Sensor Systems) Pte Ltd,Data Scientist,Singapore - North-East - Ang Mo Kio,1 Ang Mo Kio Electronics Park Road Singapore,Electrical & Electronics,"<div class=""unselectable wrap-text"" id=""job_de...",Min 2 years (Senior Executive),Aboveexpectedsalary,Job Description Design and develop data analyt...,2.0,Senior Executive
2568,Talent Touche Pte Ltd,Sales Manager,Singapore - Central,101 Cecil Street Tong Eng Building #18-11 Spor...,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 5 years (Manager),Aroundexpectedsalary,Responsibilities Business development and grow...,5.0,Manager
2569,CVista HR Consulting Pte Ltd,"Senior HR Manager (East, MNC, Up to $8,000)",Singapore - East,None,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 8 years (Senior Manager),7000-8000,Key ResponsibilitiesEngage and partner with th...,8.0,Senior Manager
2570,RecruitPlus Consulting Pte Ltd,TALENT SPECIALIST(Recruitment Sales) – Up $5–1...,Singapore - Central,146 Robinson Road #08-01 Singapore 068909,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Entry Level,5000-10000,"$2,5003,000 Basic + High Commission + Performa...",1.0,Entry Level
2571,The Supreme HR Advisory Pte. Ltd.,Sales Executive 【Freight Forwarding / Logistic...,Singapore - Across Singapore,None,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Entry Level,1800-2800,Attractive Salary Package Company Benefits & I...,1.0,Entry Level
2572,(Recruitment Firm),Presales Consultant,Singapore - Central,8 Marina View #11-01 Asia Square Tower 1 Singa...,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 5 years (Senior Executive),4000-5600,SummaryThe applicant is responsible for provid...,5.0,Senior Executive

## NO INTERNSHIPS

#### Take out Internships as they affect the price prediction

In [159]:
interns = jobstreet_df[(jobstreet_df['Title'].str.contains('Intern')) & ((jobstreet_df.Seniority == 'Entry Level') | (jobstreet_df.Seniority == 'None'))]

In [160]:
jobstreet_df.drop(interns.index, axis=0, inplace=True)

In [163]:
jobstreet_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2559 entries, 0 to 2572
Data columns (total 11 columns):
Company            2559 non-null object
Title              2559 non-null object
Location           2559 non-null object
Address            2559 non-null object
Industry           2559 non-null object
Job Description    2559 non-null object
Seniority          2559 non-null object
Salary             2559 non-null object
JD                 2559 non-null object
Min Years Exp      2454 non-null float64
Job Level          2559 non-null object
dtypes: float64(1), object(10)
memory usage: 239.9+ KB

## FIX TITLE

#### Create the Base Title Feature

In [168]:
jobstreet_df.Title.value_counts()

Business Analyst                                                                    75
Data Scientist                                                                      37
Data Analyst                                                                        28
Business Intelligent Analyst/ Data and Market Analysis/ Immediate                   16
Business System Analyst / Central / $6K ) Logistics MNC / Dynamics AX / ERP         12
Business Process Analyst / Bank / $3500 - $5000                                     12
URGENT: Business Analyst (Changi, SAP, MNC)                                         11
Recruitment Consultant                                                              11
VP, Business Data Analyst, Enterprise Data Strategy, Data Management Office         10
VP/AVP, EDAG Project Analyst, Data Management Office                                 9
Business Application Analyst (Finance, WMS & Data Management)                        9
Senior ERP Business Analyst - SyteLine                                               9
Business Data Analyst (Retail Analytics,Tableau/BI,$4K+Good Bonus,CBD)               9
Research Scientist (2-year contract), Living Analytics Research Centre               8
Data Engineer                                                                        8
Business Intelligent Analyst/ Procurement Support/ FMCG/ Immediate                   8
Helpdesk Analyst                                                                     8
Senior Financial Analyst                                                             8
[PERM] Data Analyst (Python/Spark/Big Data) - (European IT MNC/ West/ S$7K++)        8
Senior Business Intelligence Engineer(Analytics)-(Euro IT MNC/$7.5K/5Days/ West)     8
CRM Operations Analyst ~ MNC                                                         7
IT Business Analyst                                                                  7
Credit Analyst | 5mths | Up to $4K | CBD (GLEZ)                                      7
Business Development Manager                                                         7
VP/AVP, Data Scientist, Big Data Analytics Group, Data Management Office             7
Scientist (Data Analytics) / I2R (A*STAR) -18/I2R/0003                               7
System Analyst                                                                       7
APAC Business Analyst – Specialty chemicals                                          7
Financial Analyst | 12mths | Up to $4.5K | Changi Biz Park (GLEZ)                    7
Business Analyst (SEA)- Business Partnering                                          7
                                                                                    ..
Material Coordinator and Analyst (Urgent, West, Heavy Machinery or Automotive)       1
Senior Manager/Senior Executive (Data Science Unit), Planning and Organization       1
Account Executive, ASEAN                                                             1
SCIENTIST (Microbiology ISO17025 / Up To $6000 / East)                               1
Compliance Analyst, Manager (contract)                                               1
Assistant / Manager, Marketing                                                       1
Digital Data Analyst ($7K/B2B/ SQL/ MNC) ref:JT                                      1
$6K up/Temp Business/Finance Analyst/Luxury MNC                                      1
Sales & Marketing Executive                                                          1
Data Analyst ( Sales Admin)- Contract                                                1
Front end and UX developer                                                           1
R&D Firmware Engineer (28705)                                                        1
HR Assistant Manager | 1yr | Up to $4.5K | Clementi (GLEZ)                           1
Events Executive                                                                     1
Business Analyst - (007TG)                                                           1
Rewards Analyst - (18000081)                                                         1
Senior Research Scientist (1-year contract), Living Analytics Research Centre        1
Manager, Business Development (Telecommunication Technology)                         1
Specialist, Sales (Based in Australia)                                               1
Manager, Learning & Talent Management                                                1
Business Intelligence Specialist                                                     1
Accounting & Financial Analyst                                                       1
Data Scientist (Mfg/ Semiconductor industry) (SSO 410626)                            1
System Analyst (Technical Support, ERP system, Microsoft Dynamics)                   1
Business Support Analyst - (1800008G)                                                1
SAP Business Analyst - $4500                                                         1
Senior IT Business Analyst (2 year contract)                                         1
Sales Exec , Panel Glass / Building Material & Construction Industry/ 5 days         1
Corporate Support Manager                                                            1
Business Planning Analyst - COO Office                                               1
Name: Title, Length: 1127, dtype: int64

In [170]:
def base_title(x):
    if 'Data Scientist' in x:
        return 'DS'
    elif 'Data Analyst' in x:
        return 'DA'
    elif 'Business Analyst' in x:
        return 'BA'
    elif 'Business Intelligent' in x:
        return 'BI'
    elif 'Business Intelligence' in x:
        return 'BI'
    elif 'Scientist' in x:
        return 'RS'  ## Research Scientist
    else:
        return 'OTHER'

In [171]:
jobstreet_df['Base Title'] = jobstreet_df['Title'].apply(base_title)

In [172]:
jobstreet_df['Base Title'].value_counts()

OTHER    1400
BA        558
DA        232
RS        154
DS        115
BI        100
Name: Base Title, dtype: int64

In [173]:
jobstreet_df[jobstreet_df['Base Title'] == 'DS']

,Company,Title,Location,Address,Industry,Job Description,Seniority,Salary,JD,Min Years Exp,Job Level,Base Title
147,Building and Construction Authority (BCA),Data Analyst / Data Scientist (Economic Resear...,Singapore - Central,"52 Jurong Gateway Road, #11-01, Singapore 608550",Government/Defence,"<div class=""unselectable wrap-text"" id=""job_de...",Min 1 year (Junior Executive),Aroundexpectedsalary,ResponsibilitiesYou will help to identify valu...,1.0,Junior Executive,DS
152,HRnet One Pte Ltd,Data And Research Analyst (Data Scientist),Singapore - Central,391A Orchard Road #23-06 Ngee Ann City Tower A,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 3 years (Senior Executive),5500-7000,Responsibilities Conduct research in the areas...,3.0,Senior Executive,DS
201,(Recruitment Firm),Data Scientist / Analyst ( UP $7K/ JURONG/ PhD...,Singapore - West,None,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 2 years (Manager),6000-7000,UP $7K / MNC Jurong Area AWS + BONUS PHD / Mas...,2.0,Manager,DS
217,(Recruitment Firm),Data Scientist / Analyst ( UP $7K/ JURONG/ PhD...,Singapore - West,None,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 2 years (Manager),6000-7000,UP $7K / MNC Jurong Area AWS + BONUS PHD / Mas...,2.0,Manager,DS
784,"National University of Singapore, Office of Hu...",Data Scientist - (008J6),Singapore - Across Singapore - Singapore,None,Education,"<div class=""unselectable wrap-text"" id=""job_de...",Entry Level,None,1. Work with Industry Partners in Challenging ...,1.0,Entry Level,DS
785,(Recruitment Firm),Data Scientist,Singapore - Across Singapore - Singapore,None,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Junior Executive,6000-10000,about the companyOur client is expanding their...,1.0,Junior Executive,DS
791,United Overseas Bank Limited (UOB),"VP/AVP, Data Scientist, Big Data Analytics Gro...",Singapore - Across Singapore - Singapore,None,Banking/Financial Services,"<div class=""unselectable wrap-text"" id=""job_de...",Min 5 years (Senior Executive),Aboveexpectedsalary,TheData Management Office (DMO)is a business f...,5.0,Senior Executive,DS
792,United Overseas Bank Limited (UOB),"VP/AVP, Data Scientist, Big Data Analytics Gro...",Singapore - Across Singapore - Singapore,None,Banking/Financial Services,"<div class=""unselectable wrap-text"" id=""job_de...",Min 5 years (Senior Executive),Aboveexpectedsalary,TheData Management Office (DMO)is a business f...,5.0,Senior Executive,DS
794,MBA Michael Bailey Associates Pte Ltd,Data Scientist x2,Singapore - Central - Queenstown,None,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 3 years (Non-Executive),4500-6000,"Responsible for applying Data Science, i.e. Ma...",3.0,Non-Executive,DS
795,RGF Talent Solutions Singapore Pte Ltd,Machine Learning Engineer/ Data Scientist (JO-...,Singapore - Across Singapore,71 Robinson Road Singapore #0504 Singapore 068895,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 2 years (Senior Executive),Aboveexpectedsalary,About The ClientOur cliennt is leading Ad Netw...,2.0,Senior Executive,DS
796,Medtronic,Senior Supply Chain Data Scientist,Singapore - East - Pasir Ris,"50 Pasir Panjang Rd, Singapore 117440",Healthcare/Medical,"<div class=""unselectable wrap-text"" id=""job_de...",Min 3 years (Senior Executive),4000-5000,The Data Scientist will be responsible for des...,3.0,Senior Executive,DS
797,DBS Bank Limited,"VP / AVP, Data Scientist, Investment and Tradi...",Singapore - Across Singapore - Singapore,None,Banking/Financial Services,"<div class=""unselectable wrap-text"" id=""job_de...",Senior Manager,None,Business Function Group Technology and Operati...,NaN,Senior Manager,DS
798,TNO,Data Scientist Autonomous & Electric Vehicles,Singapore - Across Singapore,2 Science Park Drive,Science & Technology,"<div class=""unselectable wrap-text"" id=""job_de...",Min 5 years (Senior Executive),5000-7000,We are hiring a professional data scientist to...,5.0,Senior Executive,DS
799,Capita Pte Ltd,Data Scientist,Singapore - Central,"8 Marina View, #11-01, Asia Square Tower 1 Sin...",Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 5 years (Senior Executive),5000-7000,URGENT! Data ScientistJob DescriptionThe RoleA...,5.0,Senior Executive,DS
800,SEEK International - Global Delivery Pod,Data Scientist,Malaysia - Kuala Lumpur,Persiaran Capsquare Kuala Lumpur Federal Terri...,Computer/Information Technology (Software),"<div class=""unselectable wrap-text"" id=""job_de...",Min 3 years (Senior Executive),Belowexpectedsalary,The Role\r\n\r\n\r\nThe SEEK Group are committ...,3.0,Senior Executive,DS
804,"National University of Singapore, Office of Hu...",Data Scientist - (008J6),Singapore - Across Singapore - Singapore,None,Education,"<div class=""unselectable wrap-text"" id=""job_de...",Entry Level,None,1. Work with Industry Partners in Challenging ...,1.0,Entry Level,DS
805,(Recruitment Firm),Data Scientist,Singapore - Across Singapore - Singapore,None,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Junior Executive,6000-10000,about the companyOur client is expanding their...,1.0,Junior Executive,DS
811,United Overseas Bank Limited (UOB),"VP/AVP, Data Scientist, Big Data Analytics Gro...",Singapore - Across Singapore - Singapore,None,Banking/Financial Services,"<div class=""unselectable wrap-text"" id=""job_de...",Min 5 years (Senior Executive),Aboveexpectedsalary,TheData Management Office (DMO)is a business f...,5.0,Senior Executive,DS
812,United Overseas Bank Limited (UOB),"VP/AVP, Data Scientist, Big Data Analytics Gro...",Singapore - Across Singapore - Singapore,None,Banking/Financial Services,"<div class=""unselectable wrap-text"" id=""job_de...",Min 5 years (Senior Executive),Aboveexpectedsalary,TheData Management Office (DMO)is a business f...,5.0,Senior Executive,DS
814,MBA Michael Bailey Associates Pte Ltd,Data Scientist x2,Singapore - Central - Queenstown,None,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 3 years (Non-Executive),4500-6000,"Responsible for applying Data Science, i.e. Ma...",3.0,Non-Executive,DS
815,RGF Talent Solutions Singapore Pte Ltd,Machine Learning Engineer/ Data Scientist (JO-...,Singapore - Across Singapore,71 Robinson Road Singapore #0504 Singapore 068895,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 2 years (Senior Executive),Aboveexpectedsalary,About The ClientOur cliennt is leading Ad Netw...,2.0,Senior Executive,DS
816,Medtronic,Senior Supply Chain Data Scientist,Singapore - East - Pasir Ris,"50 Pasir Panjang Rd, Singapore 117440",Healthcare/Medical,"<div class=""unselectable wrap-text"" id=""job_de...",Min 3 years (Senior Executive),4000-5000,The Data Scientist will be responsible for des...,3.0,Senior Executive,DS
817,DBS Bank Limited,"VP / AVP, Data Scientist, Investment and Tradi...",Singapore - Across Singapore - Singapore,None,Banking/Financial Services,"<div class=""unselectable wrap-text"" id=""job_de...",Senior Manager,None,Business Function Group Technology and Operati...,NaN,Senior Manager,DS
818,TNO,Data Scientist Autonomous & Electric Vehicles,Singapore - Across Singapore,2 Science Park Drive,Science & Technology,"<div class=""unselectable wrap-text"" id=""job_de...",Min 5 years (Senior Executive),5000-7000,We are hiring a professional data scientist to...,5.0,Senior Executive,DS
819,Capita Pte Ltd,Data Scientist,Singapore - Central,"8 Marina View, #11-01, Asia Square Tower 1 Sin...",Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 5 years (Senior Executive),5000-7000,URGENT! Data ScientistJob DescriptionThe RoleA...,5.0,Senior Executive,DS
820,SEEK International - Global Delivery Pod,Data Scientist,Malaysia - Kuala Lumpur,Persiaran Capsquare Kuala Lumpur Federal Terri...,Computer/Information Technology (Software),"<div class=""unselectable wrap-text"" id=""job_de...",Min 3 years (Senior Executive),Belowexpectedsalary,The Role\r\n\r\n\r\nThe SEEK Group are committ...,3.0,Senior Executive,DS
824,Good Job Creations (Singapore) Pte Ltd,Data Scientist / Lead Machine Learning Enginee...,Singapore - Central,None,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 2 years (Senior Executive),6000-10000,[Order Number1807-50829]Responsibilities Lead ...,2.0,Senior Executive,DS
825,Infineon Technologies,Contract - Data Scientist for Business Analyti...,Singapore - Central - Kallang - Kallang,8 Kallang Sector Singapore,Semiconductor/Wafer Fabrication,"<div class=""unselectable wrap-text"" id=""job_de...",Min 1 year (Entry Level),Aboveexpectedsalary,Part of your life. Part of tomorrow. We make l...,1.0,Entry Level,DS
826,United Overseas Bank Limited (UOB),"VP/AVP, Data Scientist, Big Data Analytics Gro...",Singapore - Across Singapore - Singapore,None,Banking/Financial Services,"<div class=""unselectable wrap-text"" id=""job_de...",Min 5 years (Senior Executive),Aboveexpectedsalary,TheData Management Office (DMO)is a business f...,5.0,Senior Executive,DS
827,UPS Asia Group Pte. Ltd.,APAC Data Scientist-047522,Singapore - East,UPS House 22 Changi South Avenue 2,Transportation/Logistics,"<div class=""unselectable wrap-text"" id=""job_de...",Entry Level,Belowexpectedsalary,SummaryThe Data Scientist implements advanced ...,1.0,Entry Level,DS
...,...,...,...,...,...,...,...,...,...,...,...,...
907,None,Senior Data Scientist,Singapore - Central,6 Shenton Way #32-00 DBS Building Tower 2,Consulting (Business & Management),"<div class=""unselectable wrap-text"" id=""job_de...",Min 5 years (Manager),6800-9500,Your role at DeloitteAs a Senior Data Scientis...,5.0,Manager,DS
908,TODAY'S CAREER PTE. LTD.,Data Scientist (5 days/ Semiconductor/ Mfg ) (...,Singapore - East - Tampines / Changi,None,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 3 years (Senior Executive),Aroundexpectedsalary,5 days work weekSemiconductorChangi / Tampines...,3.0,Senior Executive,DS
909,Reeracoen Singapore Pte Ltd,Data Analytics / Data Scientist *Central 4K~8K...,Singapore - Central - Raffles Quay,Raffles Quay,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 3 years (Junior Executive),4000-8000,Ref.26616Job description IndustrySoftware/...,3.0,Junior Executive,DS
910,nSearch Global Pte Ltd,Senior Data Scientist - Data Mining / Analytic...,Singapore - Central,None,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 5 years (Manager),Aboveexpectedsalary,One of Asias leading organizations is looking ...,5.0,Manager,DS
911,Achieve Career Consultant Pte Ltd,(Analysis) Data Scientist - (Listed IT MNC/$6K...,Singapore - Across Singapore,6 Shenton Way Tower 1 #39-03 Singapore 068809,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 2 years (Junior Executive),6000-8500,"S$6,000 to S$8,500 + AWS + Performance Bonus G...",2.0,Junior Executive,DS
912,The CAP Consulting Group Pte Ltd,Data Scientist – Marketing and trading with gl...,Singapore - Central,9 Temasek Boulevard Singapore,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 4 years (Manager),Aboveexpectedsalary,Has min 4 years of data scientist experience g...,4.0,Manager,DS
913,Hudson Global Resources ( HQ ),Data Scientist,Singapore - Across Singapore - Singapore,None,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Junior Executive,None,Major Multi-nations Company in Singapore Newl...,1.0,Junior Executive,DS
914,TODAY'S CAREER PTE. LTD.,Data Scientist (Mfg/ Semiconductor industry) (...,Singapore - East - Changi - Changi / Tampines,None,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 3 years (Senior Executive),Aboveexpectedsalary,5 days work weekMfg/ SemiconductorChangi / Tam...,3.0,Senior Executive,DS
915,Tokyo Electron Singapore Pte Ltd,Semiconductor Manufacturing Equipment Data Sci...,Singapore - East - Changi,"4 Changi North Street 1, Hermes Epitek Centre,...",Semiconductor/Wafer Fabrication,"<div class=""unselectable wrap-text"" id=""job_de...",Min 3 years (Senior Executive),4000-7000,Responsibilities\r\nTo integrate TELs tool and...,3.0,Senior Executive,DS
916,BIGO TECHNOLOGY PTE. LTD.,Data Scientist (NLP),Singapore - Central - Orchard - Ngee Ann City,Singapore,Telecommunication,"<div class=""unselectable wrap-text"" id=""job_de...",Min 3 years (Senior Executive),Aboveexpectedsalary,We are launching our third engineering hub in ...,3.0,Senior Executive,DS
917,(Recruitment Firm),Data Scientist,Singapore - Central,1 Wallich Street #09-02 Guoco Tower Singapore ...,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 5 years (Junior Executive),5000-7000,Job Scope Work closely with your business to i...,5.0,Junior Executive,DS
918,Hudson Global Resources ( HQ ),Data Scientist,Singapore - Across Singapore - Singapore,None,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Junior Executive,None,Major Multi-nations Company in Singapore Newl...,1.0,Junior Executive,DS
1803,Infineon Technologies,Data Scientist - Business Intelligence and Ana...,Singapore - Central - Kallang - Kallang,8 Kallang Sector Singapore,Semiconductor/Wafer Fabrication,"<div class=""unselectable wrap-text"" id=""job_de...",Min 5 years (Non-Executive),Aboveexpectedsalary,Part of your life. Part of tomorrow. We make l...,5.0,Non-Executive,DS
1933,(Recruitment Firm),Data Scientist,Singapore - Across Singapore - Singapore,None,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Junior Executive,6000-10000,about the companyOur client is expanding their...,1.0,Junior Executive,DS
2008,Medtronic,Senior Supply Chain Data Scientist,Singapore - East - Pasir Ris,"50 Pasir Panjang Rd, Singapore 117440",Healthcare/Medical,"<div class=""unselectable wrap-text"" id=""job_de...",Min 3 years (Senior Executive),4000-5000,The Data Scientist will be responsible for des...,3.0,Senior Executive,DS
2028,Medtronic,Senior Supply Chain Data Scientist,Singapore - East - Pasir Ris,"50 Pasir Panjang Rd, Singapore 117440",Healthcare/Medical,"<div class=""unselectable wrap-text"" id=""job_de...",Min 3 years (Senior Executive),4000-5000,The Data Scientist will be responsible for des...,3.0,Senior Executive,DS
2049,Capita Pte Ltd,Data Scientist,Singapore - Central,"8 Marina View, #11-01, Asia Square Tower 1 Sin...",Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 5 years (Senior Executive),5000-7000,URGENT! Data ScientistJob DescriptionThe RoleA...,5.0,Senior Executive,DS
2068,Capita Pte Ltd,Data Scientist,Singapore - Central,"8 Marina View, #11-01, Asia Square Tower 1 Sin...",Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 5 years (Senior Executive),5000-7000,URGENT! Data ScientistJob DescriptionThe RoleA...,5.0,Senior Executive,DS
2078,SEEK International - Global Delivery Pod,Data Scientist,Malaysia - Kuala Lumpur,Persiaran Capsquare Kuala Lumpur Federal Terri...,Computer/Information Technology (Software),"<div class=""unselectable wrap-text"" id=""job_de...",Min 3 years (Senior Executive),Belowexpectedsalary,The Role\r\n\r\n\r\nThe SEEK Group are committ...,3.0,Senior Executive,DS
2125,UPS Asia Group Pte. Ltd.,APAC Data Scientist-047522,Singapore - East,UPS House 22 Changi South Avenue 2,Transportation/Logistics,"<div class=""unselectable wrap-text"" id=""job_de...",Entry Level,Belowexpectedsalary,SummaryThe Data Scientist implements advanced ...,1.0,Entry Level,DS
2234,FORTUNE SUN ASIA PTE LTD,Senior Data Scientist,Singapore - Across Singapore,None,Others,"<div class=""unselectable wrap-text"" id=""job_de...",Min 3 years (Senior Manager),9000-12600,Company Introduction.\r\nJob Description Senio...,3.0,Senior Manager,DS
2307,Spencer Ogden,Data Scientist,Singapore - Central,"One Raffles Place, Office Tower 2, #34-61 Sing...",Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 2 years (Senior Executive),Aboveexpectedsalary,Data ScientistAre you looking to be exposed to...,2.0,Senior Executive,DS
2393,Centre for Strategic Infocomm Technologies (CSIT),Data Scientist,Singapore - West,CSIT Building 30 Science Park Road Science Par...,Government/Defence,"<div class=""unselectable wrap-text"" id=""job_de...",Min 3 years (Junior Executive),Aboveexpectedsalary,Job Scope Apply statistical and machine learni...,3.0,Junior Executive,DS
2447,None,FMCG Data Scientist (Smart Manufacturing Group),Singapore - West,1 Clean Tech Loop Singapore,R&D,"<div class=""unselectable wrap-text"" id=""job_de...",Min 1 year (Non-Executive),Aroundexpectedsalary,"About the Agency for Science, Technology and R...",1.0,Non-Executive,DS
2454,None,FMCG Data Scientist,Singapore - West,1 Clean Tech Loop Singapore,R&D,"<div class=""unselectable wrap-text"" id=""job_de...",Min 2 years (Non-Executive),2500-3500,"About the Agency for Science, Technology and R...",2.0,Non-Executive,DS
2459,Mediacorp Pte Ltd,Data Scientist,Singapore - West,"1 Stars Avenue, Singapore 138507",Entertainment/Media,"<div class=""unselectable wrap-text"" id=""job_de...",Entry Level,Aroundexpectedsalary,Serve as primary source of data insights suppo...,1.0,Entry Level,DS
2479,Mediacorp Pte Ltd,Data Scientist,Singapore - West,"1 Stars Avenue, Singapore 138507",Entertainment/Media,"<div class=""unselectable wrap-text"" id=""job_de...",Entry Level,Aroundexpectedsalary,Serve as primary source of data insights suppo...,1.0,Entry Level,DS
2495,Michael Page,Data Scientist - R & Python,Singapore - Central,One Raffles Place Tower 2 #09-61 Singapore 048616,Human Resources Management/Consulting,"<div class=""unselectable wrap-text"" id=""job_de...",Min 5 years (Senior Executive),Aboveexpectedsalary,An exciting opportunity to work in one of the ...,5.0,Senior Executive,DS
2548,ST Electronics (Satcom & Sensor Systems) Pte Ltd,Data Scientist,Singapore - North-East - Ang Mo Kio,1 Ang Mo Kio Electronics Park Road Singapore,Electrical & Electronics,"<div class=""unselectable wrap-text"" id=""job_de...",Min 2 years (Senior Executive),Aboveexpectedsalary,Job Description Design and develop data analyt...,2.0,Senior Executive,DS
2567,ST Electronics (Satcom & Sensor Systems) Pte Ltd,Data Scientist,Singapore - North-East - Ang Mo Kio,1 Ang Mo Kio Electronics Park Road Singapore,Electrical & Electronics,"<div class=""unselectable wrap-text"" id=""job_de...",Min 2 years (Senior Executive),Aboveexpectedsalary,Job Description Design and develop data analyt...,2.0,Senior Executive,DS

### Fix Location

In [175]:
jobstreet_df['Location'].value_counts()

Singapore - Central                                                              899
Singapore - Across Singapore - Singapore                                         326
Singapore - Across Singapore                                                     317
Singapore - West                                                                 291
Singapore - East                                                                  75
Singapore - North-East                                                            39
None                                                                              32
Singapore - Central - Downtown Core - Cityhall                                    24
Singapore - Central - Downtown Core                                               22
Singapore - North                                                                 19
Singapore - East - Paya Lebar                                                     17
Singapore - Central - Kallang - Kallang                                           14
Singapore - Central - Orchard - 111 Somerset                                      14
Singapore - North-East - Ang Mo Kio                                               11
Singapore - Central - Tanjong Pagar                                               10
Singapore - Central - Downtown Core - Tanjong Pagar                                8
Singapore - Across Singapore - Tanjong Pagar                                       8
Across Singapore                                                                   7
Singapore - Central - Bukit Merah                                                  7
Singapore - East - Changi                                                          7
Singapore - Central - Labrador Park                                                7
Singapore - Central - Raffles Place                                                7
Singapore - Central - Downtown Core - Raffles Place                                7
Singapore - Across Singapore - singapore                                           7
Singapore - West - Others - Pasir Panjang                                          7
Singapore - West - Gul Circle                                                      6
Singapore - West - Tuas                                                            6
Singapore - East - Tampines                                                        6
Singapore - West - Clementi                                                        6
Singapore - West - Jurong East                                                     6
                                                                                ...
Singapore - Central - Bishan - 1 Raffles Institution Lane S575954                  1
Singapore - West - IMM Building                                                    1
Singapore - Across Singapore - SG                                                  1
Singapore - East - Bedok - Chai Chee                                               1
Singapore - West - Others - Ayer Rajah Crescent                                    1
Singapore - West - Alexandra Road                                                  1
Singapore - Central - Chinatown                                                    1
Singapore - Central - Benoi                                                        1
Singapore - West - Alexandra (near MRT)                                            1
Singapore - Central - Downtown Core - Shaw Tower (close to Bugis MRT station)      1
Singapore - Central - Mosque Street                                                1
Singapore - East - ubi                                                             1
Singapore - West - Others - Science Park 2                                         1
Singapore - East - Tampines / Changi                                               1
Singapore - Central - Downtown Core - CBD                                          1
Singapore - East - Others - Kaki Bukit                                             1
Singapore - Central - Others - Duxton Hill                                         1
Singapore - Central - Changi Business Park                                         1
Singapore - East - Loyang Way                                                      1
Singapore - West - Jurong West - 7 Tractor Road                                    1
Singapore - North-East - Seletar - Seletar                                         1
Australia - Across Australia                                                       1
Singapore - West - Tuas - 3 Tuas South Avenue 4                                    1
Singapore - Central - Kallang - Bendemeer                                          1
Singapore - North - Woodlands - 24A Senoko South Road                              1
Singapore - West - Choa Chu Kang - Science park                                    1
Singapore - Central - Raffles Place, Telok Ayer                                    1
Singapore - East - UBI                                                             1
Singapore - West - Jurong East - International Business Park                       1
Singapore - East - Changi - Airline Road                                           1
Name: Location, Length: 198, dtype: int64

In [177]:
aus = jobstreet_df[jobstreet_df['Location'] == 'Australia - Across Australia'] ## WTF

In [178]:
jobstreet_df.drop(aus.index, axis=0, inplace=True)

In [179]:
jobstreet_df['Location'].value_counts()

Singapore - Central                                                              899
Singapore - Across Singapore - Singapore                                         326
Singapore - Across Singapore                                                     317
Singapore - West                                                                 291
Singapore - East                                                                  75
Singapore - North-East                                                            39
None                                                                              32
Singapore - Central - Downtown Core - Cityhall                                    24
Singapore - Central - Downtown Core                                               22
Singapore - North                                                                 19
Singapore - East - Paya Lebar                                                     17
Singapore - Central - Orchard - 111 Somerset                                      14
Singapore - Central - Kallang - Kallang                                           14
Singapore - North-East - Ang Mo Kio                                               11
Singapore - Central - Tanjong Pagar                                               10
Singapore - Central - Downtown Core - Tanjong Pagar                                8
Singapore - Across Singapore - Tanjong Pagar                                       8
Singapore - Central - Downtown Core - Raffles Place                                7
Singapore - Central - Bukit Merah                                                  7
Singapore - East - Changi                                                          7
Singapore - West - Others - Pasir Panjang                                          7
Singapore - Central - Labrador Park                                                7
Singapore - Across Singapore - singapore                                           7
Singapore - Central - Raffles Place                                                7
Across Singapore                                                                   7
Singapore - West - Tuas                                                            6
Singapore - West - Clementi                                                        6
Singapore - Central - East                                                         6
Singapore - West - Gul Circle                                                      6
Singapore - North - Yishun                                                         6
                                                                                ...
Singapore - Central - Downtown Core - Shaw Tower (close to Bugis MRT station)      1
Singapore - West - Alexandra (near MRT)                                            1
Singapore - Central - Kallang                                                      1
Singapore - Central - Bishan - Jalan Pemimpin                                      1
Singapore - Across Singapore - Singapore River                                     1
Singapore - Central - Mosque Street                                                1
Singapore - Central - Downtown Core - CBD                                          1
Singapore - Central - Queenstown - Alexandra                                       1
Singapore - West - Jurong East - Ng Teng Fong General Hospital                     1
Singapore - East - Others - Kaki Bukit                                             1
Singapore - East - Bedok - Chai Chee                                               1
Singapore - Central - Braddell                                                     1
Singapore - West - Others - Ayer Rajah Crescent                                    1
Singapore - Central - Orchard - Ngee Ann City                                      1
Singapore - Central - Toa Payoh                                                    1
Singapore - West - Others - Joo Koon Circle                                        1
Singapore - Central - Kallang - Boon Keng, Bendemeer Road                          1
Singapore - West - Jurong West - 14 Tractor Road                                   1
Thailand - Bangkok                                                                 1
Singapore - North - Woodlands - 24A Senoko South Road                              1
Singapore - West - Joo Koon                                                        1
Singapore - North-East - Seletar - Seletar                                         1
Singapore - Central - Raffles Quay                                                 1
Singapore - West - Jurong West - 7 Tractor Road                                    1
Singapore - Central - Beach Road                                                   1
Singapore - West - IMM Building                                                    1
Singapore - West - Others - Science Park 2                                         1
Singapore - East - Tampines / Changi                                               1
Singapore - Central - Others - Duxton Hill                                         1
Singapore - East - Changi - Airline Road                                           1
Name: Location, Length: 197, dtype: int64

In [180]:
thai = jobstreet_df[jobstreet_df['Location'] == 'Thailand - Bangkok'] ## WTF NOPE

In [184]:
jobstreet_df.drop(thai.index, axis=0, inplace=True)

In [185]:
jobstreet_df['Location'].value_counts()

Singapore - Central                                                              899
Singapore - Across Singapore - Singapore                                         326
Singapore - Across Singapore                                                     317
Singapore - West                                                                 291
Singapore - East                                                                  75
Singapore - North-East                                                            39
None                                                                              32
Singapore - Central - Downtown Core - Cityhall                                    24
Singapore - Central - Downtown Core                                               22
Singapore - North                                                                 19
Singapore - East - Paya Lebar                                                     17
Singapore - Central - Orchard - 111 Somerset                                      14
Singapore - Central - Kallang - Kallang                                           14
Singapore - North-East - Ang Mo Kio                                               11
Singapore - Central - Tanjong Pagar                                               10
Singapore - Central - Downtown Core - Tanjong Pagar                                8
Singapore - Across Singapore - Tanjong Pagar                                       8
Singapore - Central - Labrador Park                                                7
Singapore - Across Singapore - singapore                                           7
Singapore - Central - Raffles Place                                                7
Singapore - East - Changi                                                          7
Singapore - Central - Downtown Core - Raffles Place                                7
Singapore - West - Others - Pasir Panjang                                          7
Across Singapore                                                                   7
Singapore - Central - Bukit Merah                                                  7
Singapore - West - Tuas                                                            6
Singapore - West - Jurong East                                                     6
Singapore - Central - East                                                         6
Singapore - West - Clementi                                                        6
Singapore - West - Gul Circle                                                      6
                                                                                ...
Singapore - Central - Downtown Core - Shaw Tower (close to Bugis MRT station)      1
Singapore - West - Alexandra (near MRT)                                            1
Singapore - Central - Kallang                                                      1
Singapore - Central - Bishan - Jalan Pemimpin                                      1
Singapore - Across Singapore - Singapore River                                     1
Singapore - Central - Mosque Street                                                1
Singapore - Central - Downtown Core - CBD                                          1
Singapore - Central - Queenstown - Alexandra                                       1
Singapore - West - Jurong East - Ng Teng Fong General Hospital                     1
Singapore - East - Others - Kaki Bukit                                             1
Singapore - East - Bedok - Chai Chee                                               1
Singapore - North-East - singapore                                                 1
Singapore - Central - Braddell                                                     1
Singapore - West - Others - Ayer Rajah Crescent                                    1
Singapore - Central - Orchard - Ngee Ann City                                      1
Singapore - Central - Toa Payoh                                                    1
Singapore - West - Others - Joo Koon Circle                                        1
Singapore - Central - Kallang - Boon Keng, Bendemeer Road                          1
Singapore - West - Jurong West - 14 Tractor Road                                   1
Singapore - North - Woodlands - 24A Senoko South Road                              1
Singapore - West - Joo Koon                                                        1
Singapore - North-East - Seletar - Seletar                                         1
Singapore - Central - Raffles Quay                                                 1
Singapore - West - Jurong West - 7 Tractor Road                                    1
Singapore - Central - Beach Road                                                   1
Singapore - West - IMM Building                                                    1
Singapore - West - Others - Science Park 2                                         1
Singapore - East - Tampines / Changi                                               1
Singapore - Central - Others - Duxton Hill                                         1
Singapore - East - Changi - Airline Road                                           1
Name: Location, Length: 196, dtype: int64

In [192]:
not_in_sg = jobstreet_df[~jobstreet_df['Location'].str.contains('Singapore|None')]

In [193]:
jobstreet_df.drop(not_in_sg.index, axis=0, inplace=True)

In [194]:
jobstreet_df['Location'].value_counts()

Singapore - Central                                                              899
Singapore - Across Singapore - Singapore                                         326
Singapore - Across Singapore                                                     317
Singapore - West                                                                 291
Singapore - East                                                                  75
Singapore - North-East                                                            39
None                                                                              32
Singapore - Central - Downtown Core - Cityhall                                    24
Singapore - Central - Downtown Core                                               22
Singapore - North                                                                 19
Singapore - East - Paya Lebar                                                     17
Singapore - Central - Orchard - 111 Somerset                                      14
Singapore - Central - Kallang - Kallang                                           14
Singapore - North-East - Ang Mo Kio                                               11
Singapore - Central - Tanjong Pagar                                               10
Singapore - Central - Downtown Core - Tanjong Pagar                                8
Singapore - Across Singapore - Tanjong Pagar                                       8
Singapore - Central - Raffles Place                                                7
Singapore - Central - Labrador Park                                                7
Across Singapore                                                                   7
Singapore - Central - Bukit Merah                                                  7
Singapore - Central - Downtown Core - Raffles Place                                7
Singapore - West - Others - Pasir Panjang                                          7
Singapore - East - Changi                                                          7
Singapore - Across Singapore - singapore                                           7
Singapore - Central - East                                                         6
Singapore - West - Jurong East                                                     6
Singapore - West - Tuas                                                            6
Singapore - West - Gul Circle                                                      6
Singapore - North - Yishun                                                         6
                                                                                ...
Singapore - Central - Tanglin - 352 Tanglin Road                                   1
Singapore - Central - Queenstown - Biopolis Road                                   1
Singapore - Central - Downtown Core - Shaw Tower (close to Bugis MRT station)      1
Singapore - West - Alexandra (near MRT)                                            1
Singapore - Central - Bishan - Jalan Pemimpin                                      1
Singapore - Across Singapore - Singapore River                                     1
Singapore - Central - Mosque Street                                                1
Singapore - East - Others - Kaki Bukit                                             1
Singapore - West - Joo Koon                                                        1
Singapore - East - Tampines / Changi                                               1
Singapore - East - Paya Lebar - Paya Lebar Square                                  1
Singapore - North-East - singapore                                                 1
Singapore - Central - Braddell                                                     1
Singapore - West - Others - Ayer Rajah Crescent                                    1
Singapore - Central - Orchard - Ngee Ann City                                      1
Singapore - Central - Toa Payoh                                                    1
Singapore - West - Others - Joo Koon Circle                                        1
Singapore - Central - Kallang - Boon Keng, Bendemeer Road                          1
Singapore - West - Jurong West - 14 Tractor Road                                   1
Singapore - East - Bedok - Chai Chee                                               1
Singapore - West - Others - Science Park 2                                         1
Singapore - North - Woodlands - 24A Senoko South Road                              1
Singapore - North-East - Seletar - Seletar                                         1
Singapore - Central - Raffles Quay                                                 1
Singapore - Central - Downtown Core - CBD                                          1
Singapore - West - Jurong West - 7 Tractor Road                                    1
Singapore - East - Loyang Way                                                      1
Singapore - Central - Beach Road                                                   1
Singapore - West - IMM Building                                                    1
Singapore - East - Changi - Airline Road                                           1
Name: Location, Length: 192, dtype: int64

In [195]:
jobstreet_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2544 entries, 0 to 2572
Data columns (total 12 columns):
Company            2544 non-null object
Title              2544 non-null object
Location           2544 non-null object
Address            2544 non-null object
Industry           2544 non-null object
Job Description    2544 non-null object
Seniority          2544 non-null object
Salary             2544 non-null object
JD                 2544 non-null object
Min Years Exp      2439 non-null float64
Job Level          2544 non-null object
Base Title         2544 non-null object
dtypes: float64(1), object(11)
memory usage: 258.4+ KB

## PITSTOP! - to_csv('Jobstreet_Ziig_FEng')

In [196]:
jobstreet_df.to_csv('Jobstreet_Ziig_FEng.csv')